#!/bin/sh -e
#
# vl_check_drivers
#
# Written by VersaLogic Corporation, March 2017
#
# This script is used to check and update the attributes ofthe VersaLogic 
# device driver device /dev/cgos so that VersaLogics' API VersaAPI can be 
# run as a non-root user.
# 
# ***** Variable declarations. *****
VERSION=1.0.0;
VL_DRIVE_DEVICE="/dev/cgos";
# **********************************

# ***** Check for read/write permissions of the device. *****

if [ -w "$VL_DRIVE_DEVICE" ]
then
    chmod 0666 "$VL_DRIVE_DEVICE";
fi
# ***********************************************************

exit 0
