# This is the network config written by 'subiquity'
network:
  ethernets:
    enp2s0:
      addresses:
      - 192.168.6.2/24
      gateway4: 255.255.255.0
    enp0s31f6:
      dhcp4: true
      nameservers:
        addresses: []
        search: []
  version: 2
